name: C/C++ CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: make testcpp
    - name: profile
      run: pip3 install --user gprof2dot && make cprofile.svg
    - name: leaks
      run: make leaks
